Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,27 +24,35 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Setup SSH
-        uses: webfactory/ssh-agent@v0.5.3
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      # - name: Setup SSH
+      #   uses: webfactory/ssh-agent@v0.5.3
+      #   with:
+      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Create project directory on EC2
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "mkdir -p ${{ env.PROJECT_DIR }}"
+      # - name: Create project directory on EC2
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "mkdir -p ${{ env.PROJECT_DIR }}"
           
-      - name: Copy files to EC2
-        run: |
-          scp -o StrictHostKeyChecking=no -r * ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.PROJECT_DIR }}
+      # - name: Copy files to EC2
+      #   run: |
+      #     scp -o StrictHostKeyChecking=no -r * ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.PROJECT_DIR }}
           
-      - name: Run build on EC2
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "cd ${{ env.PROJECT_DIR }} && chmod +x ./gradlew && ./gradlew build --warning-mode all --scan"
-          if [[ $? -ne 0 ]]; then
-            echo "Build failed, cleaning up..."
-            ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "rm -rf ${{ env.PROJECT_DIR }}"
-            exit 1
-          fi
+      # - name: Run build on EC2
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "cd ${{ env.PROJECT_DIR }} && chmod +x ./gradlew && ./gradlew build --warning-mode all --scan"
+      #     if [[ $? -ne 0 ]]; then
+      #       echo "Build failed, cleaning up..."
+      #       ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "rm -rf ${{ env.PROJECT_DIR }}"
+      #       exit 1
+      #     fi
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+        shell: bash
+      
+      - name: Build with Gradle
+        run: ./gradlew build
+        shell: bash
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -53,8 +61,9 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET__ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Archive build artifacts
-        run: zip -r ${{ github.sha }}.zip build/* .
+      - name: Make zip file
+        run: zip -r ${{ github.sha }}.zip .
+        shell: bash
 
 
       - name: Upload to S3
